config/routes.rb
Ece517proj1::Application.routes.draw do

  match 'users/all', controller: 'users', action: 'index'
  match '/signup', controller: 'users', action: 'new'
  match '/signin', controller: 'sessions', action: 'new'
  match '/signout', controller: 'sessions', action: 'destroy'

  match '/demote', controller: 'users', action: 'demote'
  match '/promote', controller: 'users', action: 'promote'

  match '/like', controller: 'posts', action: 'vote'
  match '/unlike', controller: 'posts', action: 'unvote'

  match '/new_comment', controller: 'posts', action: 'new_comment'
  match '/show_voted', controller: 'posts', action: 'show_voted'

  match 'search', controller:'application', action: 'search'

  resources :sessions

  resources :categories

  resources :posts

  resources :users











   root :to => "sessions#new"


end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :email, :password, :password_confirmation, :admin
  has_secure_password

  has_many :posts, :dependent => :destroy
  has_many :votes, foreign_key: "user_id", :dependent => :destroy

  before_save { |user| user.email = email.downcase}
  before_save :create_remember_token

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :username,
            presence: true,
            uniqueness: true,
            length: { in: 3..50 }

  validates :email,
            presence: true,
            uniqueness: { case_sensitive: false },
            format: { with: VALID_EMAIL_REGEX }

  validates :password,
            presence: true,
            confirmation: true,  #password_confirmation attr
            length: { in: 6..50 }

  validates :password_confirmation,
           presence: true

  def voted?(post)
    votes.find_by_post_id(post.id)
  end

  def vote!(post)
    votes.create!(post_id: post.id)
  end

  def unvote!(post)
    votes.find_by_post_id(post.id).destroy
  end

  def self.search(search)
    if search
      find(:all, :conditions => ['username LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end

  private
    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:edit, :update, :destroy, :promote, :demote]
  before_filter :correct_user,   only: [:edit, :update, :destroy]
  before_filter :admin_user,     only: [:promote, :demote]

  #show all user
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  #show current user info
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  #create user
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        sign_in @user
        format.html { redirect_to root_path, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # edit user
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  #delete user
  def destroy
    @user = User.find(params[:id])

    if current_user?(@user) && current_user.admin?
      redirect_to root_path, notice: "admin can not delete self"
    else
      @user.destroy
      respond_to do |format|
        format.html { redirect_to root_url }
        format.json { head :no_content }
      end
    end
  end

  def promote
    respond_to do |format|
      if User.find(params[:id]).update_attribute(:admin, true)
        format.html { redirect_to users_all_path, notice: 'User was successfully promoted to admin.' }
        format.json { head :no_content }
      else
        format.html { redirect_to users_all_path, notice: 'Fail to update user.' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end

  end

  def demote
    respond_to do |format|
      if User.find(params[:id]).update_attribute(:admin, false)
        format.html { redirect_to users_all_path, notice: 'User was successfully demoted.' }
        format.json { head :no_content }
      else
        format.html { redirect_to users_all_path, notice: 'Fail to update user.' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def liked
    @user = User.find(params[:id])
    @title = "Posts that #{@user.username} liked"

    render 'show_liked'
  end

  private
    def correct_user
      @user = User.find(params[:id])
      #if the @user != current_user
      #  or if @user.admin != true
      if !current_user?(@user)
        redirect_to root_path, notice: "You do not have the permission to perform this operation" unless current_user.admin?
      end
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
        <%= render 'layouts/error_messages', object: f.object %>

        <%= f.label :username %>
        <%= f.text_field :username %>

        <%= f.label :email %>
        <%= f.text_field :email %>

        <%= f.label :password %>
        <%= f.password_field :password %>

        <%= f.label :password_confirmation, "Password Confirmation" %>
        <%= f.password_field :password_confirmation %>

        <%= f.submit class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>



app/views/users/_list_posts.html.erb
<% if @user.posts.first.nil? %>
    No post
<% else %>
    <table>
      <tr>
        <th>Title</th>
        <th>Category</th>
        <th>Created at</th>
      </tr>
      <% @user.posts.all(:order => "created_at ASC").each do |post| %>
          <tr>
            <td><%= link_to post.title, post %></td>
            <td><%= link_to post.category.name, post.category %></td>
            <td><%= "#{time_ago_in_words post.created_at} ago"%></td>
            <% if signed_in? %>
              <% if current_user?(post.user) or current_user.admin? %>
                <td><%= link_to 'Edit', edit_post_path(post) %></td>
                <td><%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <% end %>
            <% end %>
          </tr>
      <% end %>
    </table>
<% end %>

app/views/users/_list_votes.html.erb
<% if @user.votes.first.nil? %>
    No vote
<% else %>
    <table>
      <tr>
        <th>Title</th>
        <th>Author</th>
        <th>Category</th>
        <th>Voted at</th>
      </tr>
      <% @user.votes.all(:order => "created_at ASC").each do |vote| %>
          <tr>
            <td><%= link_to vote.post.title, vote.post %></td>
            <td><%= link_to vote.post.user.username, vote.post.user %></td>
            <td><%= link_to vote.post.category.name, vote.post.category %></td>
            <td><%= "#{time_ago_in_words vote.created_at} ago"%></td>
            <% if signed_in? %>
                <% if current_user?(vote.user) %>
                    <td><%= link_to 'unvote', {controller: 'posts', action: 'unvote', id: vote.post.id} %></td>
                <% end %>
            <% end %>
          </tr>
      <% end %>
    </table>
<% end %>

app/views/users/_search_result.html.erb
<% @users.each do |user| %>
    <% @user = user %>
    <h4><%= link_to @user.username, @user %></h4>
    <%= render 'users/list_posts' %>
<% end %>



app/views/users/edit.html.erb
<% provide(:title, 'Edit User') %>

<h1>Editing user</h1>

<%= render 'form' %>




app/views/users/index.html.erb
<% provide(:title, "Users") %>

<h1>Listing Users</h1>

<% if @users.empty? %>
  No user <br/>
<% else %>
<table>
  <tr>
    <th>Username</th>
    <th>Email</th>
    <th>Created at</th>
    <th>Update at</th>
    <th>Credential</th>
  </tr>

  <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.username, user %></td>
        <td><%= user.email %></td>
        <td><%= time_ago_in_words user.created_at %> ago.</td>
        <td><%= time_ago_in_words user.updated_at %> ago.</td>
        <td>
          <% if user.admin? %>
            admin
            <% if signed_in? %>
                <% if current_user.admin? %>
                    <td>
                      <%= link_to('revoke', {:controller => 'users', :action => 'demote', :id => user.id}) unless current_user?(user) %>
                    </td>
                <% end %>
            <% end %>
          <% else %>
            normal user
            <% if signed_in? %>
                <% if current_user.admin? %>
                    <td>
                      <%= link_to('promote', {:controller => 'users', :action => 'promote', :id => user.id} )unless current_user?(user) %>
                    </td>
                <% end %>
            <% end %>
          <% end %>
        </td>

        <% if signed_in? %>
            <% if current_user?(user) or current_user.admin? %>
                <td><%= link_to 'Edit', edit_user_path(user) %></td>
                <td><%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' } unless current_user?(user) and current_user.admin?%></td>
            <% end %>
        <% end %>
      </tr>
  <% end %>
</table>

<% end %>




app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>

<h1>Sign Up</h1>

<%= render 'form' %>



app/views/users/show.html.erb
<p>
    <h1><%= @user.username %></h1>
</p>

<p>
    <b>Email:</b>
    <%= @user.email %>
</p>

<p>
  <b>Member since:</b>
  <%= @user.created_at.to_date %>
</p>

<p>
  <b>Credential:</b>
  <% if @user.admin? %>
    admin
    <% if signed_in? %>
      <% if current_user.admin? %>
        <%= link_to('revoke', {:controller => 'users', :action => 'demote', :id => @user.id}) unless current_user?(@user) %>
      <% end %>
    <% end %>
  <% else %>
    normal user
    <% if signed_in? %>
      <% if current_user.admin? %>
        <%= link_to('promote', {:controller => 'users', :action => 'promote', :id => @user.id} )unless current_user?(@user) %>
      <% end %>
    <% end %>
  <% end %>
</p>

<p>
  <b>Posts and Comments:</b>
  <%= render 'list_posts' %>
</p>

<p>
  <b>Votes:</b>
  <%= render 'list_votes' %>
</p>

<p>
 <% if current_user?(@user) or current_user.admin? %>
   <%= link_to 'Edit', edit_user_path(@user) %> |
   <%= link_to 'Delete', @user, method: :delete, data: { confirm: 'Are you sure?' } unless current_user?(@user) and current_user.admin? %>
 <% end %>
</p>

app/views/users/show_liked.html.erb
<h2>
  <% "Post that #{@post.username} Liked " %>
</h2>

<% if @user.votes.empty? %>
    No liked post
<% else %>
    <table>
      <tr>
        <th>Title</th>
        <th>Author</th>
        <th>Category</th>
        <th>Created at</th>
        <th>Updated at</th>
      </tr>

      <% @user.votes.all do |vote| %>
      <tr>
        <td><%= link_to vote.post.title, post %></td>
        <td><%= link_to vote.post.user.username, vote.post.user %></td>
        <td><%= link_to vote.post.category.name, vote.post.category %></td>

        <td><%= time_ago_in_words vote.post.created_at %> ago.</td>
        <td><%= time_ago_in_words vote.post.updated_at %> ago.</td>
      </tr>
      <% end %>
    </table><br/>
<% end %>




