config/routes.rb
Ece517proj1::Application.routes.draw do

  match 'users/all', controller: 'users', action: 'index'
  match '/signup', controller: 'users', action: 'new'
  match '/signin', controller: 'sessions', action: 'new'
  match '/signout', controller: 'sessions', action: 'destroy'

  match '/demote', controller: 'users', action: 'demote'
  match '/promote', controller: 'users', action: 'promote'

  match '/like', controller: 'posts', action: 'vote'
  match '/unlike', controller: 'posts', action: 'unvote'

  match '/new_comment', controller: 'posts', action: 'new_comment'
  match '/show_voted', controller: 'posts', action: 'show_voted'

  match 'search', controller:'application', action: 'search'

  resources :sessions

  resources :categories

  resources :posts

  resources :users











   root :to => "sessions#new"


end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts, :dependent => :destroy

  attr_accessible :name

  validates :name,
            presence: true,
            length: { minimum: 2 }

  def self.search(search)
    if search
      find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :signed_in_user, only: [:new, :create, :edit, :update, :destroy]
  before_filter :admin_user, only: [:new, :create, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all(:order => "created_at ASC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to categories_path, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@category) do |f| %>
        <%= render 'layouts/error_messages', object: f.object %>
            <%= f.label :name %>
            <%= f.text_field :name %>

            <%= f.submit class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/categories/_list_posts.erb
<% if @category.posts.first.nil? %>
    No post
<% else %>
<table>
  <tr>
    <th>Name</th>
    <th>Created by</th>
    <th>Created at</th>
    <th>Latest activity</th>
  </tr>

  <% @category.posts.all(:order => "updated_at DESC").each do |post| %>
      <tr>
        <% if post.parent_post_id.nil? %>
            <td><%= link_to post.title, post %></td>
            <td><%= link_to post.user.username, post.user %></td>
            <td><%= "#{time_ago_in_words post.created_at} ago"%></td>
            <td><%= "#{time_ago_in_words post.updated_at} ago"%></td>

            <% if signed_in? %>
                <% if current_user?(post.user) or current_user.admin? %>
                    <td><%= link_to 'Edit', edit_post_path(post) %></td>
                    <td><%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                <% end %>
            <% end %>
        <% end %>
      </tr>
  <% end %>

</table>
<% end %>

app/views/categories/_search_result.html.erb
<% if @categories.empty? %>
    No posts
<% else %>
<% @categories.each do |category| %>
    <% @category = category %>
    <h4><%= link_to @category.name, @category %></h4>
    <%= render 'categories/list_posts' %>
<% end %>
<% end %>

app/views/categories/edit.html.erb
<% provide(:title, "Edit Category") %>

<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<% provide(:title, "Categories") %>
<h1>Listing Categories</h1>

<% if @categories.empty? %>
    No category <br/>
<% else %>
<table>
  <tr>
    <th>Name</th>
    <th>Post Count</th>
    <th>Created at</th>
    <th>Latest Activity</th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td>
      <%= link_to category.name, category %>
    </td>

    <td>
      <%= category.posts.where(:parent_post_id => nil).count %> posts
    </td>

    <td>
      <%= time_ago_in_words category.created_at %> ago
    </td>

    <td>
      <% if category.posts.empty? %>
          No post created yet.
      <% else %>
          <%= time_ago_in_words category.posts.all(:order => "updated_at DESC").first.updated_at %> ago by
      <% end %>
    </td>

    <% if signed_in? %>
        <% if current_user.admin? %>
            <td><%= link_to 'Edit', edit_category_path(category) %></td>
            <td><%= link_to 'Delete', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
    <% end %>
  </tr>
<% end %>
</table>

<% end %>
<br/>
<% if signed_in? %>
    <% if current_user.admin?%>
        <%= link_to 'New Category', new_category_path, class: "btn btn-large btn-primary" %>
    <% end %>
<% end %>


app/views/categories/new.html.erb
<% provide(:title, "New Category") %>
<h1>New Category</h1>

<%= render 'form' %>



app/views/categories/show.html.erb
<% provide(:title, "Categories | #{@category.name}") %>
<h1><%= @category.name %></h1>

<p><%= render 'list_posts' %></p>


<% if signed_in? %>
    <%= link_to 'New Post', new_post_path, class: "btn btn-large btn-primary" %>
<% end %>