config/routes.rb
Ece517proj1::Application.routes.draw do

  match 'users/all', controller: 'users', action: 'index'
  match '/signup', controller: 'users', action: 'new'
  match '/signin', controller: 'sessions', action: 'new'
  match '/signout', controller: 'sessions', action: 'destroy'

  match '/demote', controller: 'users', action: 'demote'
  match '/promote', controller: 'users', action: 'promote'

  match '/like', controller: 'posts', action: 'vote'
  match '/unlike', controller: 'posts', action: 'unvote'

  match '/new_comment', controller: 'posts', action: 'new_comment'
  match '/show_voted', controller: 'posts', action: 'show_voted'

  match 'search', controller:'application', action: 'search'

  resources :sessions

  resources :categories

  resources :posts

  resources :users











   root :to => "sessions#new"


end

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
        The form contains <%= pluralize(object.errors.count, "error") %>.
      </div>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li>* <%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    NCSU ECE 517 Project 1 by Hao Liu and Travis Folsom
  </small>
  <nav>
    <ul>
      <li><%= link_to "Show all users", users_all_url %></li>
      <li><%= link_to "Show all categories", categories_url %></li>
      <li><%= link_to "Show all posts", posts_url %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">

      <nav>
        <%= render 'layouts/search_bar' %>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <% if signed_in? %>
              <li><%= link_to current_user.username, current_user %></li>
              <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
          <% else %>
              <li><%= link_to "Sign in", signin_path %></li>
              <li><%= link_to "Sign up", signup_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>


app/views/layouts/_search_bar.html.erb
<%= form_tag search_path, :method => 'get' do |f| %>
    <ul class="nav pull-left">
      <li><font color=white>Search by</font></li>
      <li>
         <%= select_tag(:search_by,
                        options_for_select(
                                [['all', 'all'],
                                 ['username', 'username'],
                                 ['post content', 'post'],
                                 ['category name', 'category']])) %>
      </li>
      <li><%= text_field_tag :search, params[:search] %></li>
      <li><%= submit_tag "Search", :name => nil , class: "btn btn-small btn-primary"%></li>
    </ul>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "alert alert-#{key}") %>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
</div>
</body>
</html>